### ISSUE TITLE
Evaluation Protocol

### ISSUE THREAD

**Issue by MoayedHajiAli** [Text-to-Audio/Make-An-Audio#12]
Greetings,
I am wondering what is the backbone that you used for CLAP score, since the scale of the numbers seems to be different from other baseline such as audioldm. If you also have the script for calculating the CLAP score for reference, I would greatly appreciate it.
Thank you!

**Comment by Darius-H** [comment]
> Greetings, I am wondering what is the backbone that you used for CLAP score, since the scale of the numbers seems to be different from other baseline such as audioldm. If you also have the script for calculating the CLAP score for reference, I would greatly appreciate it. Thank you!

We uses CLAP_weights_2022.pth in https://huggingface.co/microsoft/msclap

**Comment by MoayedHajiAli** [comment]
Thank you!
