### ISSUE TITLE
the config file of CLAP

### ISSUE THREAD

**Issue by yypyyds** [Text-to-Audio/Make-An-Audio#8]
I have trained a model of my datasets and now I want to calculate the CLAP scores.
But when I ran the cal__clap_score.py script, I got a FileNotFoundError:  [Errno 2] No such file or directory: 'useful_ckpts/CLAP/config.yml'
I have downloaded the CLAP_weights_2022.pth through the link in #4 , but that huggingface repo didn't give a config file.
So where can I get the config file?

**Comment by Darius-H** [comment]
The config file is provided in useful_ckpts/CLAP/config.yml .
